[package]
name = "shadowresources"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["libs/snes-gfx"]

[dependencies]
byteorder="1.5.0"
image ="0.25.2"
bitstream-io="2.5.3"
serde = { version = "1.0.2", features = ["derive"] }
serde_json = "1.0"
snes-gfx = {path="./libs/snes-gfx"}